### ISSUE TITLE
gradlew run oder gradle run

### ISSUE THREAD

**Issue by LeHarter** [dialogos-project/jython-plugin#1]
Beim jython Clienten funktioniert gradlew runClient, um den Clienten zu starten. Hier in der Dokumentation des jython plugins steht, man solle den Befehl gradlew run eingeben. Das funktioniert aber nicht, es kommt die Fehlermeldung "der Befehl gradlew ist nicht bekannt.". Run gradle funktioniert hingegen. Ist das ein Rechtschreibfehler?
Viele Grüße,
Leonie Harter

**Comment by alexanderkoller** [comment]
Das war kein Tippfehler, sondern ich hatte vergessen, die gradlew-Dateien für Windows einzuchecken. Machen Sie mal ein git pull und versuchen Sie es nochmal.

**Comment by LeHarter** [comment]
Vielen Dank, jetzt funktioniert gradlew.
